---
apiVersion: v1
kind: Service
metadata:
  name: toleration-injection
  namespace: kube-system
  labels:
    app: toleration-injection
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: toleration-injection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toleration-injection
  namespace: kube-system
  labels:
    app: toleration-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toleration-injection
  template:
    metadata:
      name: toleration-injection
      labels:
        app: toleration-injection
    spec:
      containers:
        - name: toleration-injection
          image: gcr.io/quatreapp/k8s-toleration-injection-webhook:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 16Mi
          envFrom:
            - configMapRef:
                name: toleration-config
