---
apiVersion: v1
kind: Service
metadata:
  name: toleration-injection-webhook
  namespace: kube-system
  labels:
    app: toleration-injection-webhook
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: toleration-injection-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toleration-injection-webhook
  namespace: kube-system
  labels:
    app: toleration-injection-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toleration-injection-webhook
  template:
    metadata:
      name: toleration-injection-webhook
      labels:
        app: toleration-injection-webhook
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: toleration-injection-webhook
          image: gcr.io/quatreapp/k8s-toleration-injection-webhook:1.0.0-1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 16Mi
          envFrom:
            - configMapRef:
                name: toleration-config
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-key-file=/etc/webhook/certs/key.pem
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: toleration-injection-webhook-certs
